include: package:flutter_lints/flutter.yaml

#analyzer:
#  strong-mode:
#    implicit-casts: false
#    implicit-dynamic: false

linter:
  rules:
    - unnecessary_cast: ignore
    - unnecessary_null_comparison: ignore
    - avoid_function_literals_in_foreach_calls